apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.jobservice" . }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
    vaultInjectionChecksum: {{ include "harbor.jobservice.config" . | sha256sum }}
{{- if .Values.jobservice.configAnnotations }}
{{ toYaml .Values.jobservice.configAnnotations | indent 4 }}
{{- end }}
data:
  config.yml: |+
    {{- include "harbor.jobservice.config" . | indent 4 }}
